all: _mainTester.cpp
	g++ -std=c++11 _mainTester.cpp -o a
	
	
execute1:	
	./a t1.txt 1 1
	./a t1.txt 1 2
	./a t1.txt 2 1
	./a t1.txt 2 2
	./a t1.txt 3 1
	./a t1.txt 3 2

execute2:	
	./a t2.txt 1 1
	./a t2.txt 1 2
	./a t2.txt 2 1
	./a t2.txt 2 2
	./a t2.txt 3 1
	./a t2.txt 3 2

execute3:	
	./a t3.txt 1 1
	./a t3.txt 1 2
	./a t3.txt 2 1
	./a t3.txt 2 2
	./a t3.txt 3 1
	./a t3.txt 3 2

execute4:	
	./a t4.txt 1 1
	./a t4.txt 1 2
	./a t4.txt 2 1
	./a t4.txt 2 2
	./a t4.txt 3 1
	./a t4.txt 3 2

execute5:	
	./a t5.txt 1 1
	./a t5.txt 1 2
	./a t5.txt 2 1
	./a t5.txt 2 2
	./a t5.txt 3 1
	./a t5.txt 3 2

clean:
	rm  a
