all: _mainTester.cpp
	g++ -std=c++11 -o run _mainTester.cpp cpu.cpp cpuProgram.cpp memory.cpp computer.cpp cpuProgramDyn.cpp
	
	
execute:	
	./run deneme2.txt 1
	./run deneme2.txt 2
	./run deneme2.txt 0
clean:
	rm  run
