all: Myprogram

Myprogram: main.o
	g++ HW2.o  -o Myprogram

main.o: HW2.cpp
	g++ -c HW2.cpp

clean:
	rm *.o Myprogram

execute0:
	./Myprogram deneme2.txt 0 

execute1:
	./Myprogram deneme2.txt 1 

execute2:
	./Myprogram deneme2.txt 2 
